#!/bin/bash

# Path to the text file containing user names generated by getAllUsers.sh
USER_FILE="user_list.txt"

# The usage of this script, is a repeating loop that ensures the required users exist with admin access.
while true; do
    ###################################################### SCORECHECK USER #################################################
    DONOTTOUCH=(
        # Add usernames here that should not be touched by this script
    )
    ###################################################### SCORECHECK USER #################################################


    ###################################################### Delete users ###################################################
    valid_shells=(/bin/bash /bin/sh /usr/bin/zsh /usr/bin/fish)

    # Load predefined users from a text file and add 'root' as a default system user
    readarray -t predefined_users < $USER_FILE
    predefined_users+=("root")  # Keeping root as a default predefined user

    while IFS=: read -r username _ _ _ _ _ shell; do
        for valid_shell in "${valid_shells[@]}"; do
            if [[ "$shell" == "$valid_shell" ]]; then
                if ! printf '%s\n' "${predefined_users[@]}" | grep -qx "$username"; then
                    echo "User '$username' is NOT in the predefined list but has a valid shell: $shell"
                    pkill --signal SIGKILL -u $username
                    userdel -r $username || deluser $username --remove-home
                fi
                break
            fi
        done
    done < /etc/passwd

    ###################################################### ADMINS #################################################
    administratorGroup=( 
    root
    )

    for admin in "${administratorGroup[@]}"; do
        if ! id "$admin" &>/dev/null; then
            useradd -m "$admin"
            echo "User $admin created."
        fi

        if ! id "$admin" | grep -qw sudo; then
            usermod -aG sudo "$admin"
            echo "$admin added to sudo group."
        fi
    done


    ###################################################### NORMAL USERS #################################################
    normalUsers=(
        # List of normal users can be added here if needed
    )

    ############################## ADDING AND REMOVING ADMINISTRATORS

    echo "######Ensuring normal users exist and are not part of the sudo group#####"
    for user in "${normalUsers[@]}"; do
        if ! id "$user" &>/dev/null; then
            useradd -m "$user"
            echo "User $user created."
        fi
        if id "$user" | grep -qw 'sudo'; then
            gpasswd -d "$user" sudo
            echo "Removed $user from the sudo group."
        fi
    done

    sleep 30
done
